server:
  port: 9002

spring:
  application:
    name: xdclass-coupon-service

  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 39.105.31.194:8848

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.31.194:3306/xdclass_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: jisheng.LI@423
  #redis配置
  redis:
    host: 39.105.31.194
    password: 123456
    port: 8000


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#seata配置
seata:
  tx-service-group: ${spring.application.name}-group
  service:
    grouplist:
      xdclass: 127.0.0.1:8091
    vgroup-mapping:
      xdclass-coupon-service-group: xdclass
